const customerApi = 'http://localhost:5000/api/contacts';
let customers = [];
let editingCustomerId = null;
const serviceDefaults = ['New Registration', 'Ownership Transfer', 'RC Renewal', 'Driving Licence', 'Address Change'];

function customerEscape(value) { return String(value ?? '').replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]); }
function customerDate(value) { return value ? new Date(value).toLocaleDateString('en-GB') : '—'; }
function customerStatus(customer, index) { return customer.application_status || ['Under Process', 'Documents Pending', 'Completed'][index % 3]; }
function customerService(customer, index) { return customer.service_type || customer.occupation || serviceDefaults[index % serviceDefaults.length]; }
function notify(message) { const toast = document.getElementById('toast'); toast.textContent = message; toast.style.display = 'block'; setTimeout(() => { toast.style.display = 'none'; }, 2600); }
function filteredCustomers() { const search = document.getElementById('customerSearch').value.toLowerCase(); const status = document.getElementById('customerStatus').value; return customers.filter((customer, index) => { const text = `${customer.full_name} ${customer.phone} ${customer.email} ${customer.application_number || ''} ${customer.city || ''}`.toLowerCase(); return (!search || text.includes(search)) && (!status || customerStatus(customer, index) === status); }); }

function renderCustomers() {
  const rows = filteredCustomers();
  document.getElementById('customerSummary').textContent = `${rows.length} of ${customers.length} customer records`;
  document.getElementById('customerFooter').textContent = `${rows.length} customers shown`;
  document.getElementById('customerTableBody').innerHTML = rows.length ? rows.map((customer, rowIndex) => { const originalIndex = customers.indexOf(customer); const status = customerStatus(customer, originalIndex); return `<tr><td><strong>CUS-${String(customer.id).padStart(4, '0')}</strong></td><td><strong>${customerEscape(customer.full_name)}</strong></td><td>${customerEscape(customer.phone || '—')}<small>${customerEscape(customer.alternate_phone || '')}</small></td><td>${customerEscape(customer.email || '—')}</td><td>${customerEscape(customer.city || '—')}<small>${customerEscape(customer.rto_office || 'RTO Office pending')}</small></td><td>${customerEscape(customerService(customer, originalIndex))}</td><td>RTO-${1000 + Number(customer.id)}</td><td>${customerDate(customer.application_date || customer.created_at)}</td><td><span class="badge ${status === 'Completed' ? 'teal' : status === 'Documents Pending' ? 'amber' : 'blue'}">${customerEscape(status)}</span></td><td>${customerEscape(customer.assigned_employee || 'Demo User')}</td><td><button class="action-button" onclick="viewCustomer(${customer.id})">View</button> <button class="action-button" onclick="editCustomer(${customer.id})">Edit</button> <button class="action-button" onclick="deleteCustomer(${customer.id})">Delete</button></td></tr>`; }).join('') : '<tr><td colspan="11" class="empty-state">No customer records match your filters.</td></tr>';
}

async function loadCustomers() { try { const response = await fetch(`${customerApi}/all`); customers = await response.json(); } catch { customers = []; } renderCustomers(); }
function openCustomerModal(customer = null) { editingCustomerId = customer?.id || null; document.getElementById('customerModalTitle').textContent = customer ? 'Edit Customer' : 'Add Customer'; document.getElementById('customerForm').reset(); if (customer) Object.keys(customer).forEach(key => { const field = document.getElementById(key); if (field) field.value = customer[key] || ''; }); document.getElementById('customerModal').style.display = 'flex'; }
function closeCustomerModal() { document.getElementById('customerModal').style.display = 'none'; editingCustomerId = null; }
function editCustomer(id) { const customer = customers.find(item => item.id === id); if (customer) openCustomerModal(customer); }
function profileSection(title, content) { return `<section class="crm-panel"><div class="panel-heading"><h2>${title}</h2></div>${content}</section>`; }
function viewCustomer(id) { const customer = customers.find(item => item.id === id); if (!customer) return; const service = customerService(customer, customers.indexOf(customer)); document.getElementById('profileContent').innerHTML = `<div class="profile-grid"><aside class="profile-card"><div class="profile-avatar">${customerEscape(customer.full_name.slice(0, 2).toUpperCase())}</div><h2>${customerEscape(customer.full_name)}</h2><p>${customerEscape(customer.email || 'No email')}<br>${customerEscape(customer.phone || 'No mobile')}</p><div class="detail-list"><div><span>Customer ID</span><strong>CUS-${String(customer.id).padStart(4, '0')}</strong></div><div><span>City</span><strong>${customerEscape(customer.city || '—')}</strong></div><div><span>RTO Office</span><strong>${customerEscape(customer.rto_office || 'Pending')}</strong></div><div><span>Service</span><strong>${customerEscape(service)}</strong></div></div><button class="btn btn-primary" style="width:100%;margin-top:18px" onclick="editCustomer(${customer.id});closeProfile()">Edit Customer</button></aside><div><div class="tab-list"><button class="tab-button active" type="button">Overview</button><button class="tab-button" type="button">Documents</button><button class="tab-button" type="button">Vehicle</button><button class="tab-button" type="button">Policy</button><button class="tab-button" type="button">Payments</button><button class="tab-button" type="button">Follow-ups</button><button class="tab-button" type="button">History</button></div>${profileSection('Customer Details', `<div class="detail-list"><div><span>Full Name</span><strong>${customerEscape(customer.full_name)}</strong></div><div><span>Address</span><strong>${customerEscape(customer.address || '—')}</strong></div><div><span>State / Pincode</span><strong>${customerEscape(customer.state || '—')} / ${customerEscape(customer.pincode || '—')}</strong></div><div><span>Aadhaar / PAN</span><strong>${customerEscape(customer.aadhaar || 'Pending')} / ${customerEscape(customer.pan || 'Pending')}</strong></div></div>`)}${profileSection('RTO Service Details', `<div class="detail-list"><div><span>Application</span><strong>RTO-${1000 + Number(customer.id)}</strong></div><div><span>Service Type</span><strong>${customerEscape(service)}</strong></div><div><span>Status</span><strong>${customerEscape(customerStatus(customer, customers.indexOf(customer)))}</strong></div><div><span>Remarks</span><strong>${customerEscape(customer.notes || 'No remarks')}</strong></div></div>`)}</div></div>`; document.getElementById('profileModal').style.display = 'flex'; }
function closeProfile() { document.getElementById('profileModal').style.display = 'none'; }
async function deleteCustomer(id) { const customer = customers.find(item => item.id === id); if (!customer || !confirm(`Delete ${customer.full_name}?`)) return; const response = await fetch(`${customerApi}/delete/${id}`, { method: 'DELETE' }); if (response.ok) { notify('Customer deleted'); loadCustomers(); } else notify('Unable to delete customer'); }

document.addEventListener('DOMContentLoaded', () => { loadCustomers(); ['customerSearch', 'customerStatus'].forEach(id => document.getElementById(id).addEventListener('input', renderCustomers)); document.getElementById('globalCustomerSearch').addEventListener('input', event => { document.getElementById('customerSearch').value = event.target.value; renderCustomers(); }); document.getElementById('exportCustomers').addEventListener('click', () => { window.open(`${customerApi}/export/excel`, '_blank'); }); document.getElementById('customerForm').addEventListener('submit', async event => { event.preventDefault(); const payload = {}; event.target.querySelectorAll('input, select, textarea').forEach(field => { payload[field.id] = field.value; }); payload.occupation = payload.service_type; payload.notes = payload.notes || ''; const url = editingCustomerId ? `${customerApi}/update/${editingCustomerId}` : `${customerApi}/add`; const response = await fetch(url, { method: editingCustomerId ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (response.ok) { closeCustomerModal(); notify(editingCustomerId ? 'Customer updated' : 'Customer added'); loadCustomers(); } else notify('Please check the customer details'); }); });
