let followupItems = [];
let followupTab = 'today';
function followupEscape(value) { return String(value ?? '').replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]); }
function followupStore() { try { return JSON.parse(localStorage.getItem('rto-followups') || '[]'); } catch { return []; } }
function followupSave() { localStorage.setItem('rto-followups', JSON.stringify(followupItems)); }
function todayIso() { return new Date().toISOString().slice(0, 10); }
function followupBucket(item) { if (item.status === 'Completed') return 'completed'; if (item.date < todayIso()) return 'overdue'; if (item.date === todayIso()) return 'today'; return 'upcoming'; }
function followupStatusClass(status) { return status === 'Completed' ? 'teal' : status === 'Pending' ? 'amber' : 'gray'; }
function renderFollowups() { const search = document.getElementById('followupSearch').value.toLowerCase(); const type = document.getElementById('followupType').value; const rows = followupItems.filter(item => followupBucket(item) === followupTab && (!type || item.type === type) && (!search || `${item.customer} ${item.mobile} ${item.vehicle} ${item.type}`.toLowerCase().includes(search))); document.getElementById('followupTitle').textContent = { today: "Today's Follow-ups", overdue: 'Overdue Follow-ups', upcoming: 'Upcoming Follow-ups', completed: 'Completed Follow-ups' }[followupTab]; document.getElementById('followupSummary').textContent = `${rows.length} follow-up tasks`; document.getElementById('followupBody').innerHTML = rows.length ? rows.map(item => `<tr><td><strong>${followupEscape(item.customer)}</strong></td><td>${followupEscape(item.mobile)}</td><td>${followupEscape(item.vehicle || '—')}</td><td>${followupEscape(item.type)}</td><td>${followupEscape(item.service || 'General')}</td><td>${followupEscape(item.date)}<small>${followupEscape(item.time || '')}</small></td><td>${followupEscape(item.assigned || 'Demo User')}</td><td><span class="badge ${followupStatusClass(item.status)}">${followupEscape(item.status)}</span></td><td><button class="action-button" onclick="callFollowup('${followupEscape(item.mobile)}')">Call</button> <button class="action-button" onclick="whatsappFollowup('${followupEscape(item.mobile)}')">WhatsApp</button> <button class="action-button" onclick="completeFollowup('${item.id}')">Complete</button></td></tr>`).join('') : '<tr><td colspan="9" class="empty-state">No follow-ups in this queue.</td></tr>'; }
function renderFollowupKpis() { const counts = { today: followupItems.filter(item => followupBucket(item) === 'today').length, overdue: followupItems.filter(item => followupBucket(item) === 'overdue').length, upcoming: followupItems.filter(item => followupBucket(item) === 'upcoming').length, completed: followupItems.filter(item => followupBucket(item) === 'completed').length }; document.getElementById('followupKpis').innerHTML = `<article class="kpi-card"><span class="kpi-icon teal">◷</span><div><p>Today's Follow-ups</p><strong>${counts.today}</strong><small>Planned for today</small></div></article><article class="kpi-card"><span class="kpi-icon red">!</span><div><p>Overdue</p><strong>${counts.overdue}</strong><small>Need immediate action</small></div></article><article class="kpi-card"><span class="kpi-icon amber">▣</span><div><p>Upcoming</p><strong>${counts.upcoming}</strong><small>Next 7 days</small></div></article><article class="kpi-card"><span class="kpi-icon blue">✓</span><div><p>Completed</p><strong>${counts.completed}</strong><small>Closed tasks</small></div></article>`; }
function seedFollowups() { if (followupItems.length) return; const now = new Date(); const date = now.toISOString().slice(0, 10); followupItems = [{ id: 1, customer: 'John Doe', mobile: '9876543211', vehicle: 'MH01AB1234', type: 'Document Pending', service: 'New Registration', date, time: '10:30', assigned: 'Demo User', status: 'Pending', remarks: 'Collect Aadhaar and RC' }, { id: 2, customer: 'Sara Khan', mobile: '9123456781', vehicle: 'DL05XY4321', type: 'Policy Renewal', service: 'Insurance Renewal', date, time: '14:00', assigned: 'Demo User', status: 'Pending' }, { id: 3, customer: 'Ravi Sharma', mobile: '9988776651', vehicle: 'MH12CD1111', type: 'RC Renewal', service: 'RC Renewal', date: new Date(now.getTime() - 86400000).toISOString().slice(0, 10), time: '11:00', assigned: 'Demo User', status: 'Pending' }, { id: 4, customer: 'Meera Joshi', mobile: '9012345678', vehicle: '', type: 'Payment Pending', service: 'Ownership Transfer', date: new Date(now.getTime() + 86400000).toISOString().slice(0, 10), time: '12:30', assigned: 'Demo User', status: 'Pending' }]; followupSave(); }
function showFollowupToast(message) { const toast = document.getElementById('toast'); toast.textContent = message; toast.style.display = 'block'; setTimeout(() => { toast.style.display = 'none'; }, 2400); }
function openFollowupModal() { document.getElementById('followupModal').style.display = 'flex'; }
function closeFollowupModal() { document.getElementById('followupModal').style.display = 'none'; }
function callFollowup(number) { window.location.href = `tel:${number}`; }
function whatsappFollowup(number) { window.open(`https://wa.me/${number.replace(/\D/g, '')}`, '_blank'); }
function completeFollowup(id) { const item = followupItems.find(entry => String(entry.id) === String(id)); if (item) { item.status = 'Completed'; followupSave(); renderFollowupKpis(); renderFollowups(); showFollowupToast('Follow-up completed'); } }

document.addEventListener('DOMContentLoaded', () => { followupItems = followupStore(); seedFollowups(); renderFollowupKpis(); renderFollowups(); document.querySelectorAll('[data-followup-tab]').forEach(tab => tab.addEventListener('click', () => { document.querySelector('.tab-button.active').classList.remove('active'); tab.classList.add('active'); followupTab = tab.dataset.followupTab; renderFollowups(); })); document.getElementById('followupSearch').addEventListener('input', renderFollowups); document.getElementById('followupType').addEventListener('change', renderFollowups); document.getElementById('followupForm').addEventListener('submit', event => { event.preventDefault(); const form = event.target; const item = { id: Date.now(), customer: form.querySelector('#followupCustomer').value, mobile: form.querySelector('#followupMobile').value, vehicle: form.querySelector('#followupVehicle').value, type: form.querySelector('#followupTypeForm').value, service: form.querySelector('#followupService').value, date: form.querySelector('#followupDate').value, time: form.querySelector('#followupTime').value, assigned: form.querySelector('#followupAssigned').value, remarks: form.querySelector('#followupRemarks').value, status: 'Pending' }; followupItems.push(item); followupSave(); form.reset(); closeFollowupModal(); renderFollowupKpis(); renderFollowups(); showFollowupToast('Follow-up scheduled'); }); });
